---
title: Brain Dump
baseurl: ""
desc: I see things and try to capture it here 
about: I'm developer, architect, and project lead currently living in Pune,India.
image: "./profile.jpeg"
excerpt_separator: "<!-- more -->"
markdown: kramdown
plugin:
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 5
paginate_path: "/blog/:num/"
highlighter: rouge
permalink: pretty
collections:
  category:
    output: true
defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
