---
title: Brain Dump
baseurl: ""
desc: This site is an attempt to write what I'm learning.
about: I'm developer, architect, and project lead currently living in Pune,India.
image: https://media-exp1.licdn.com/dms/image/C5103AQGQt0Lzwwb4MA/profile-displayphoto-shrink_400_400/0?e=1598486400&v=beta&t=pjaZWjh3UIQCziZwiKLBMVOGXkBYXGBbxXXmUM6WkcI
excerpt_separator: "<!-- more -->"
markdown: kramdown
plugin:
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 5
paginate_path: "/blog/:num/"
highlighter: rouge
permalink: pretty
collections:
  category:
    output: true
defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
