---
title: Brain Dump
baseurl: ""
desc: This site is an attempt to write what I'm learning.
about: I'm developer, architect, and project lead currently living in Pune,India.
image: https://pbs.twimg.com/profile_images/2873511153/802ef67324104647fce48fb32f1b0056_400x400.jpeg
excerpt_separator: "<!-- more -->"
markdown: kramdown
plugins:
- jekyll-paginate
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 5
paginate_path: "/:num/"
highlighter: rouge
permalink: pretty
